Executando um Pipeline
dadosjusbr/alba pull request #27
Opened 2020-09-09 17:16 UTC by Lorenaps

- Criação do comando `alba run --id --dadosjusbr`
- Persistindo o resultado no banco de dados (em caso de sucesso ou de falha, pode ser verificado pelo o campo `status`)

O teste foi realizado com o pipeline feito para o tutorial do pacote executor. Os resultados no banco firam da seguinte forma:
![Captura de tela de 2020-09-09 14-10-33](https://user-images.githubusercontent.com/9660774/92630743-ac740900-f2a6-11ea-8f80-e89938c7a5f1.png)

2020-09-10 00:26 UTC, danielfireman requested changes

2020-09-10 00:26 UTC, danielfireman commented on cli/pipeline/exec.go
> +			&cli.StringFlag{Name: "month", Usage: "Month to be collected."},
Tem muito a ver com o que eu  tinha falado no outro PR. Isso não será passado via env vars?

2020-09-10 00:26 UTC, danielfireman commented on cli/pipeline/exec.go
> +		p, err = worker.SetupDadosjusBR(p, month, year)
Talvez esse setup não precise existir. Só passar o GIT_COMMIT, MONTH e YEAR via variável de  ambiente.

2020-09-10 00:26 UTC, danielfireman commented on cli/pipeline/exec.go
> +	p.Pipeline.DefaultBaseDir, _, err = worker.CloneRepository(p.Repo)
Se a gente não usa esse retorno do meio, por que retornamos?

2020-09-10 00:26 UTC, danielfireman commented on cli/pipeline/exec.go
> +type managerExecution interface {
Uma curiosidade: por que você criou essa interface?

Não estou querendo dar a entender que está errado, apenas curiosidade. Isso pois, uma vez que Go tem inferência implícita de interfaces, elas aparecem mais tarde no desenvolvimento do código. Em outros casos, as interfaces aparecem para facilitar testes.

Você está fazendo isso para facilitar os testes que virão? Ou algo assim?

2020-09-10 00:26 UTC, danielfireman commented on cli/pipeline/exec.go
> +package pipeline
pode chamar esse arquivo de run.go? Fica mais fácil associar ele ao comando run :)

2020-09-18 01:13 UTC, Lorenaps commented on cli/pipeline/exec.go
> +			&cli.StringFlag{Name: "month", Usage: "Month to be collected."},
Ajuste para utilzar variáveis de ambiente realizado.

2020-09-18 01:14 UTC, Lorenaps commented on cli/pipeline/exec.go
> +		p, err = worker.SetupDadosjusBR(p, month, year)
Ajuste para utilzar variáveis de ambiente realizado.

2020-09-18 01:14 UTC, Lorenaps commented on cli/pipeline/exec.go
> +	p.Pipeline.DefaultBaseDir, _, err = worker.CloneRepository(p.Repo)
Foi porque iria adicionar o consudo desse retorno (que era o valor do git), quando implementasse a função com as regras de negocio para os pipelines dadosjus.
Mas a partir do que conversamos no slack, essas serão variáveis padrão de todos os pipelines.
Agora o retorno esta sendo devidamente utilizado.

2020-09-18 01:16 UTC, Lorenaps commented on cli/pipeline/exec.go
> +type managerExecution interface {
Pra facilitar os testes semelhante ao que fizemos no comando add.

2020-09-18 01:16 UTC, Lorenaps commented on cli/pipeline/exec.go
> +package pipeline
Ajuste realizado.

2020-09-18 01:21 UTC, Lorenaps commented
Hoje estamos passando `GIT_COMMIT, MONTH, YEAR` e `OUTPUT_FOLDER` como padrão em todos os estágios. Mas elas seão preenchidas caso definidas no pipeline.
Por isso, atualizei também os arquivos de exemplo para o preenchimento.

2020-09-18 16:48 UTC, danielfireman approved these changes

2020-09-18 18:57 UTC, merged